name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: ğŸ” ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v6

      - name: ğŸ” Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e SC1071 -e SC2148 -e SC2128 -e SC2207 -e SC2155 -e SC2206 -e SC2296
        with:
          scandir: "."
          severity: warning

  release-please:
    name: ğŸš€ Release
    runs-on: ubuntu-latest
    needs: shellcheck
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: ğŸ•º Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
